// Code generated by go-swagger; DO NOT EDIT.

package service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllAccountParams creates a new GetAllAccountParams object
// with the default values initialized.
func NewGetAllAccountParams() *GetAllAccountParams {
	var ()
	return &GetAllAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllAccountParamsWithTimeout creates a new GetAllAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllAccountParamsWithTimeout(timeout time.Duration) *GetAllAccountParams {
	var ()
	return &GetAllAccountParams{

		timeout: timeout,
	}
}

// NewGetAllAccountParamsWithContext creates a new GetAllAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllAccountParamsWithContext(ctx context.Context) *GetAllAccountParams {
	var ()
	return &GetAllAccountParams{

		Context: ctx,
	}
}

// NewGetAllAccountParamsWithHTTPClient creates a new GetAllAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllAccountParamsWithHTTPClient(client *http.Client) *GetAllAccountParams {
	var ()
	return &GetAllAccountParams{
		HTTPClient: client,
	}
}

/*GetAllAccountParams contains all the parameters to send to the API endpoint
for the get all account operation typically these are written to a http.Request
*/
type GetAllAccountParams struct {

	/*AccountID*/
	AccountID *string
	/*Address*/
	Address *string
	/*CurrencySymbol*/
	CurrencySymbol *string
	/*ParticipantID*/
	ParticipantID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all account params
func (o *GetAllAccountParams) WithTimeout(timeout time.Duration) *GetAllAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all account params
func (o *GetAllAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all account params
func (o *GetAllAccountParams) WithContext(ctx context.Context) *GetAllAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all account params
func (o *GetAllAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all account params
func (o *GetAllAccountParams) WithHTTPClient(client *http.Client) *GetAllAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all account params
func (o *GetAllAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get all account params
func (o *GetAllAccountParams) WithAccountID(accountID *string) *GetAllAccountParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get all account params
func (o *GetAllAccountParams) SetAccountID(accountID *string) {
	o.AccountID = accountID
}

// WithAddress adds the address to the get all account params
func (o *GetAllAccountParams) WithAddress(address *string) *GetAllAccountParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the get all account params
func (o *GetAllAccountParams) SetAddress(address *string) {
	o.Address = address
}

// WithCurrencySymbol adds the currencySymbol to the get all account params
func (o *GetAllAccountParams) WithCurrencySymbol(currencySymbol *string) *GetAllAccountParams {
	o.SetCurrencySymbol(currencySymbol)
	return o
}

// SetCurrencySymbol adds the currencySymbol to the get all account params
func (o *GetAllAccountParams) SetCurrencySymbol(currencySymbol *string) {
	o.CurrencySymbol = currencySymbol
}

// WithParticipantID adds the participantID to the get all account params
func (o *GetAllAccountParams) WithParticipantID(participantID *string) *GetAllAccountParams {
	o.SetParticipantID(participantID)
	return o
}

// SetParticipantID adds the participantId to the get all account params
func (o *GetAllAccountParams) SetParticipantID(participantID *string) {
	o.ParticipantID = participantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccountID != nil {

		// query param accountId
		var qrAccountID string
		if o.AccountID != nil {
			qrAccountID = *o.AccountID
		}
		qAccountID := qrAccountID
		if qAccountID != "" {
			if err := r.SetQueryParam("accountId", qAccountID); err != nil {
				return err
			}
		}

	}

	if o.Address != nil {

		// query param address
		var qrAddress string
		if o.Address != nil {
			qrAddress = *o.Address
		}
		qAddress := qrAddress
		if qAddress != "" {
			if err := r.SetQueryParam("address", qAddress); err != nil {
				return err
			}
		}

	}

	if o.CurrencySymbol != nil {

		// query param currencySymbol
		var qrCurrencySymbol string
		if o.CurrencySymbol != nil {
			qrCurrencySymbol = *o.CurrencySymbol
		}
		qCurrencySymbol := qrCurrencySymbol
		if qCurrencySymbol != "" {
			if err := r.SetQueryParam("currencySymbol", qCurrencySymbol); err != nil {
				return err
			}
		}

	}

	if o.ParticipantID != nil {

		// query param participantId
		var qrParticipantID string
		if o.ParticipantID != nil {
			qrParticipantID = *o.ParticipantID
		}
		qParticipantID := qrParticipantID
		if qParticipantID != "" {
			if err := r.SetQueryParam("participantId", qParticipantID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
