// Code generated by go-swagger; DO NOT EDIT.

package service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "mxp/mxp-protobuf/swg/clientswg/models"
)

// GetAllAccountReader is a Reader for the GetAllAccount structure.
type GetAllAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllAccountOK creates a GetAllAccountOK with default headers values
func NewGetAllAccountOK() *GetAllAccountOK {
	return &GetAllAccountOK{}
}

/*GetAllAccountOK handles this case with default header values.

A successful response.
*/
type GetAllAccountOK struct {
	Payload *models.OrderResponseAccount
}

func (o *GetAllAccountOK) Error() string {
	return fmt.Sprintf("[GET /_v1/get_all_account][%d] getAllAccountOK  %+v", 200, o.Payload)
}

func (o *GetAllAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrderResponseAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
