// Code generated by go-swagger; DO NOT EDIT.

package service_participant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetParticipantParams creates a new GetParticipantParams object
// with the default values initialized.
func NewGetParticipantParams() *GetParticipantParams {
	var ()
	return &GetParticipantParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetParticipantParamsWithTimeout creates a new GetParticipantParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetParticipantParamsWithTimeout(timeout time.Duration) *GetParticipantParams {
	var ()
	return &GetParticipantParams{

		timeout: timeout,
	}
}

// NewGetParticipantParamsWithContext creates a new GetParticipantParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetParticipantParamsWithContext(ctx context.Context) *GetParticipantParams {
	var ()
	return &GetParticipantParams{

		Context: ctx,
	}
}

// NewGetParticipantParamsWithHTTPClient creates a new GetParticipantParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetParticipantParamsWithHTTPClient(client *http.Client) *GetParticipantParams {
	var ()
	return &GetParticipantParams{
		HTTPClient: client,
	}
}

/*GetParticipantParams contains all the parameters to send to the API endpoint
for the get participant operation typically these are written to a http.Request
*/
type GetParticipantParams struct {

	/*ID*/
	ID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get participant params
func (o *GetParticipantParams) WithTimeout(timeout time.Duration) *GetParticipantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get participant params
func (o *GetParticipantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get participant params
func (o *GetParticipantParams) WithContext(ctx context.Context) *GetParticipantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get participant params
func (o *GetParticipantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get participant params
func (o *GetParticipantParams) WithHTTPClient(client *http.Client) *GetParticipantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get participant params
func (o *GetParticipantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get participant params
func (o *GetParticipantParams) WithID(id *string) *GetParticipantParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get participant params
func (o *GetParticipantParams) SetID(id *string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetParticipantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
