// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"mxp/mxp-protobuf/swg/clientswg/client/service_account"
	"mxp/mxp-protobuf/swg/clientswg/client/service_account_balance"
	"mxp/mxp-protobuf/swg/clientswg/client/service_auth"
	"mxp/mxp-protobuf/swg/clientswg/client/service_commission"
	"mxp/mxp-protobuf/swg/clientswg/client/service_currency"
	"mxp/mxp-protobuf/swg/clientswg/client/service_order"
	"mxp/mxp-protobuf/swg/clientswg/client/service_participant"
	"mxp/mxp-protobuf/swg/clientswg/client/service_transaction"
)

// Default mxpapp HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new mxpapp HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Mxpapp {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new mxpapp HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Mxpapp {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new mxpapp client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Mxpapp {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Mxpapp)
	cli.Transport = transport

	cli.ServiceAccount = service_account.New(transport, formats)

	cli.ServiceAccountBalance = service_account_balance.New(transport, formats)

	cli.ServiceAuth = service_auth.New(transport, formats)

	cli.ServiceCommission = service_commission.New(transport, formats)

	cli.ServiceCurrency = service_currency.New(transport, formats)

	cli.ServiceOrder = service_order.New(transport, formats)

	cli.ServiceParticipant = service_participant.New(transport, formats)

	cli.ServiceTransaction = service_transaction.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Mxpapp is a client for mxpapp
type Mxpapp struct {
	ServiceAccount *service_account.Client

	ServiceAccountBalance *service_account_balance.Client

	ServiceAuth *service_auth.Client

	ServiceCommission *service_commission.Client

	ServiceCurrency *service_currency.Client

	ServiceOrder *service_order.Client

	ServiceParticipant *service_participant.Client

	ServiceTransaction *service_transaction.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Mxpapp) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.ServiceAccount.SetTransport(transport)

	c.ServiceAccountBalance.SetTransport(transport)

	c.ServiceAuth.SetTransport(transport)

	c.ServiceCommission.SetTransport(transport)

	c.ServiceCurrency.SetTransport(transport)

	c.ServiceOrder.SetTransport(transport)

	c.ServiceParticipant.SetTransport(transport)

	c.ServiceTransaction.SetTransport(transport)

}
