// Code generated by go-swagger; DO NOT EDIT.

package service_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCloseSessionParams creates a new CloseSessionParams object
// with the default values initialized.
func NewCloseSessionParams() *CloseSessionParams {

	return &CloseSessionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCloseSessionParamsWithTimeout creates a new CloseSessionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCloseSessionParamsWithTimeout(timeout time.Duration) *CloseSessionParams {

	return &CloseSessionParams{

		timeout: timeout,
	}
}

// NewCloseSessionParamsWithContext creates a new CloseSessionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCloseSessionParamsWithContext(ctx context.Context) *CloseSessionParams {

	return &CloseSessionParams{

		Context: ctx,
	}
}

// NewCloseSessionParamsWithHTTPClient creates a new CloseSessionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCloseSessionParamsWithHTTPClient(client *http.Client) *CloseSessionParams {

	return &CloseSessionParams{
		HTTPClient: client,
	}
}

/*CloseSessionParams contains all the parameters to send to the API endpoint
for the close session operation typically these are written to a http.Request
*/
type CloseSessionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the close session params
func (o *CloseSessionParams) WithTimeout(timeout time.Duration) *CloseSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the close session params
func (o *CloseSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the close session params
func (o *CloseSessionParams) WithContext(ctx context.Context) *CloseSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the close session params
func (o *CloseSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the close session params
func (o *CloseSessionParams) WithHTTPClient(client *http.Client) *CloseSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the close session params
func (o *CloseSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CloseSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
