// Code generated by go-swagger; DO NOT EDIT.

package service_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "mxp/mxp-protobuf/swg/clientswg/models"
)

// NewStartSessionParams creates a new StartSessionParams object
// with the default values initialized.
func NewStartSessionParams() *StartSessionParams {
	var ()
	return &StartSessionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStartSessionParamsWithTimeout creates a new StartSessionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartSessionParamsWithTimeout(timeout time.Duration) *StartSessionParams {
	var ()
	return &StartSessionParams{

		timeout: timeout,
	}
}

// NewStartSessionParamsWithContext creates a new StartSessionParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartSessionParamsWithContext(ctx context.Context) *StartSessionParams {
	var ()
	return &StartSessionParams{

		Context: ctx,
	}
}

// NewStartSessionParamsWithHTTPClient creates a new StartSessionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStartSessionParamsWithHTTPClient(client *http.Client) *StartSessionParams {
	var ()
	return &StartSessionParams{
		HTTPClient: client,
	}
}

/*StartSessionParams contains all the parameters to send to the API endpoint
for the start session operation typically these are written to a http.Request
*/
type StartSessionParams struct {

	/*Body*/
	Body *models.OrderAuthenticate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start session params
func (o *StartSessionParams) WithTimeout(timeout time.Duration) *StartSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start session params
func (o *StartSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start session params
func (o *StartSessionParams) WithContext(ctx context.Context) *StartSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start session params
func (o *StartSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start session params
func (o *StartSessionParams) WithHTTPClient(client *http.Client) *StartSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start session params
func (o *StartSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the start session params
func (o *StartSessionParams) WithBody(body *models.OrderAuthenticate) *StartSessionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the start session params
func (o *StartSessionParams) SetBody(body *models.OrderAuthenticate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *StartSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
