// Code generated by go-swagger; DO NOT EDIT.

package service_auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "mxp/mxp-protobuf/swg/clientswg/models"
)

// StartSessionReader is a Reader for the StartSession structure.
type StartSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StartSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStartSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStartSessionOK creates a StartSessionOK with default headers values
func NewStartSessionOK() *StartSessionOK {
	return &StartSessionOK{}
}

/*StartSessionOK handles this case with default header values.

A successful response.
*/
type StartSessionOK struct {
	Payload *models.OrderSession
}

func (o *StartSessionOK) Error() string {
	return fmt.Sprintf("[POST /v1/start_session][%d] startSessionOK  %+v", 200, o.Payload)
}

func (o *StartSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OrderSession)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
