// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AccountBalanceLockedReason account balance locked reason
// swagger:model AccountBalanceLockedReason
type AccountBalanceLockedReason struct {

	// amount
	Amount float64 `json:"amount,omitempty"`

	// contract Id
	ContractID string `json:"contractId,omitempty"`

	// order Id
	OrderID string `json:"orderId,omitempty"`

	// reason
	Reason LockedReasonLockedReason `json:"reason,omitempty"`
}

// Validate validates this account balance locked reason
func (m *AccountBalanceLockedReason) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReason(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountBalanceLockedReason) validateReason(formats strfmt.Registry) error {

	if swag.IsZero(m.Reason) { // not required
		return nil
	}

	if err := m.Reason.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("reason")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountBalanceLockedReason) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountBalanceLockedReason) UnmarshalBinary(b []byte) error {
	var res AccountBalanceLockedReason
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
