// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// DealStatusStatus deal status status
// swagger:model DealStatusStatus
type DealStatusStatus string

const (

	// DealStatusStatusCREATED captures enum value "CREATED"
	DealStatusStatusCREATED DealStatusStatus = "CREATED"

	// DealStatusStatusPERFORMED captures enum value "PERFORMED"
	DealStatusStatusPERFORMED DealStatusStatus = "PERFORMED"

	// DealStatusStatusCANCELED captures enum value "CANCELED"
	DealStatusStatusCANCELED DealStatusStatus = "CANCELED"
)

// for schema
var dealStatusStatusEnum []interface{}

func init() {
	var res []DealStatusStatus
	if err := json.Unmarshal([]byte(`["CREATED","PERFORMED","CANCELED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dealStatusStatusEnum = append(dealStatusStatusEnum, v)
	}
}

func (m DealStatusStatus) validateDealStatusStatusEnum(path, location string, value DealStatusStatus) error {
	if err := validate.Enum(path, location, value, dealStatusStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this deal status status
func (m DealStatusStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateDealStatusStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
