// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OrderCommission order commission
// swagger:model orderCommission
type OrderCommission struct {

	// amount
	Amount float64 `json:"Amount,omitempty"`

	// currency
	Currency string `json:"Currency,omitempty"`

	// receive address
	ReceiveAddress string `json:"ReceiveAddress,omitempty"`

	// remainder
	Remainder float64 `json:"Remainder,omitempty"`

	// sending address
	SendingAddress string `json:"SendingAddress,omitempty"`
}

// Validate validates this order commission
func (m *OrderCommission) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OrderCommission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCommission) UnmarshalBinary(b []byte) error {
	var res OrderCommission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
