// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OrderResponseAccountBalance order response account balance
// swagger:model orderResponse_AccountBalance
type OrderResponseAccountBalance struct {

	// query status
	QueryStatus OrderQueryStatus `json:"QueryStatus,omitempty"`

	// object
	Object *OrderAccountBalance `json:"object,omitempty"`
}

// Validate validates this order response account balance
func (m *OrderResponseAccountBalance) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQueryStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderResponseAccountBalance) validateQueryStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.QueryStatus) { // not required
		return nil
	}

	if err := m.QueryStatus.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("QueryStatus")
		}
		return err
	}

	return nil
}

func (m *OrderResponseAccountBalance) validateObject(formats strfmt.Registry) error {

	if swag.IsZero(m.Object) { // not required
		return nil
	}

	if m.Object != nil {
		if err := m.Object.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("object")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderResponseAccountBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderResponseAccountBalance) UnmarshalBinary(b []byte) error {
	var res OrderResponseAccountBalance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
