// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OrderQueryCreateAccount order query create account
// swagger:model orderQuery_CreateAccount
type OrderQueryCreateAccount struct {

	// address
	Address string `json:"address,omitempty"`

	// currency Id
	CurrencyID string `json:"currencyId,omitempty"`

	// currency name
	CurrencyName string `json:"currencyName,omitempty"`

	// owner Id
	OwnerID string `json:"ownerId,omitempty"`

	// type
	Type OrderAccountType `json:"type,omitempty"`
}

// Validate validates this order query create account
func (m *OrderQueryCreateAccount) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderQueryCreateAccount) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderQueryCreateAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderQueryCreateAccount) UnmarshalBinary(b []byte) error {
	var res OrderQueryCreateAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
