// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// OrderCurrency order currency
// swagger:model orderCurrency
type OrderCurrency struct {

	// @inject_tag: bson:"_id,omitempty"
	// Format: byte
	BsonID strfmt.Base64 `json:"bsonId,omitempty"`

	// decimal
	Decimal int64 `json:"decimal,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// symbol
	Symbol string `json:"symbol,omitempty"`

	// type
	Type CurrencyCurrencyType `json:"type,omitempty"`
}

// Validate validates this order currency
func (m *OrderCurrency) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBsonID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OrderCurrency) validateBsonID(formats strfmt.Registry) error {

	if swag.IsZero(m.BsonID) { // not required
		return nil
	}

	// Format "byte" (base64 string) is already validated when unmarshalled

	return nil
}

func (m *OrderCurrency) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("type")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *OrderCurrency) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OrderCurrency) UnmarshalBinary(b []byte) error {
	var res OrderCurrency
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
