// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// OrderTxStatus order tx status
// swagger:model orderTxStatus
type OrderTxStatus string

const (

	// OrderTxStatusUNCONFIRMED captures enum value "UNCONFIRMED"
	OrderTxStatusUNCONFIRMED OrderTxStatus = "UNCONFIRMED"

	// OrderTxStatusCOLLATERALIZED captures enum value "COLLATERALIZED"
	OrderTxStatusCOLLATERALIZED OrderTxStatus = "COLLATERALIZED"

	// OrderTxStatusSAVED captures enum value "SAVED"
	OrderTxStatusSAVED OrderTxStatus = "SAVED"

	// OrderTxStatusCONFIRMED captures enum value "CONFIRMED"
	OrderTxStatusCONFIRMED OrderTxStatus = "CONFIRMED"

	// OrderTxStatusCANCELED captures enum value "CANCELED"
	OrderTxStatusCANCELED OrderTxStatus = "CANCELED"
)

// for schema
var orderTxStatusEnum []interface{}

func init() {
	var res []OrderTxStatus
	if err := json.Unmarshal([]byte(`["UNCONFIRMED","COLLATERALIZED","SAVED","CONFIRMED","CANCELED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderTxStatusEnum = append(orderTxStatusEnum, v)
	}
}

func (m OrderTxStatus) validateOrderTxStatusEnum(path, location string, value OrderTxStatus) error {
	if err := validate.Enum(path, location, value, orderTxStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this order tx status
func (m OrderTxStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateOrderTxStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
