// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package structs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// enum structs
type AccountType int32

const (
	AccountType_INTERNAL AccountType = 0
	AccountType_EXTERNAL AccountType = 1
	AccountType_SYSTEM   AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "INTERNAL",
	1: "EXTERNAL",
	2: "SYSTEM",
}

var AccountType_value = map[string]int32{
	"INTERNAL": 0,
	"EXTERNAL": 1,
	"SYSTEM":   2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

type Account_Status int32

const (
	Account_INACTIVE Account_Status = 0
	Account_ACTIVE   Account_Status = 1
)

var Account_Status_name = map[int32]string{
	0: "INACTIVE",
	1: "ACTIVE",
}

var Account_Status_value = map[string]int32{
	"INACTIVE": 0,
	"ACTIVE":   1,
}

func (x Account_Status) String() string {
	return proto.EnumName(Account_Status_name, int32(x))
}

func (Account_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8, 0}
}

type AccountBalance_LockedReason__LockedReason int32

const (
	AccountBalance_LockedReason_REASON_UNVERIFIED_LOCKED AccountBalance_LockedReason__LockedReason = 0
	AccountBalance_LockedReason_REASON_CONTRACT_LOCKED   AccountBalance_LockedReason__LockedReason = 1
	AccountBalance_LockedReason_REASON_ORDER_LOCKED      AccountBalance_LockedReason__LockedReason = 2
	AccountBalance_LockedReason_REASON_COMMISSION_LOCKED AccountBalance_LockedReason__LockedReason = 3
	AccountBalance_LockedReason_REASON_WITHDRAWAL_LOCKED AccountBalance_LockedReason__LockedReason = 4
)

var AccountBalance_LockedReason__LockedReason_name = map[int32]string{
	0: "REASON_UNVERIFIED_LOCKED",
	1: "REASON_CONTRACT_LOCKED",
	2: "REASON_ORDER_LOCKED",
	3: "REASON_COMMISSION_LOCKED",
	4: "REASON_WITHDRAWAL_LOCKED",
}

var AccountBalance_LockedReason__LockedReason_value = map[string]int32{
	"REASON_UNVERIFIED_LOCKED": 0,
	"REASON_CONTRACT_LOCKED":   1,
	"REASON_ORDER_LOCKED":      2,
	"REASON_COMMISSION_LOCKED": 3,
	"REASON_WITHDRAWAL_LOCKED": 4,
}

func (x AccountBalance_LockedReason__LockedReason) String() string {
	return proto.EnumName(AccountBalance_LockedReason__LockedReason_name, int32(x))
}

func (AccountBalance_LockedReason__LockedReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9, 0, 0}
}

type EventNewAccount struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventNewAccount) Reset()         { *m = EventNewAccount{} }
func (m *EventNewAccount) String() string { return proto.CompactTextString(m) }
func (*EventNewAccount) ProtoMessage()    {}
func (*EventNewAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *EventNewAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventNewAccount.Unmarshal(m, b)
}
func (m *EventNewAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventNewAccount.Marshal(b, m, deterministic)
}
func (m *EventNewAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventNewAccount.Merge(m, src)
}
func (m *EventNewAccount) XXX_Size() int {
	return xxx_messageInfo_EventNewAccount.Size(m)
}
func (m *EventNewAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_EventNewAccount.DiscardUnknown(m)
}

var xxx_messageInfo_EventNewAccount proto.InternalMessageInfo

func (m *EventNewAccount) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type EventAccountUpdate struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventAccountUpdate) Reset()         { *m = EventAccountUpdate{} }
func (m *EventAccountUpdate) String() string { return proto.CompactTextString(m) }
func (*EventAccountUpdate) ProtoMessage()    {}
func (*EventAccountUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *EventAccountUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAccountUpdate.Unmarshal(m, b)
}
func (m *EventAccountUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAccountUpdate.Marshal(b, m, deterministic)
}
func (m *EventAccountUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAccountUpdate.Merge(m, src)
}
func (m *EventAccountUpdate) XXX_Size() int {
	return xxx_messageInfo_EventAccountUpdate.Size(m)
}
func (m *EventAccountUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAccountUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EventAccountUpdate proto.InternalMessageInfo

func (m *EventAccountUpdate) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type EventAccountBalanceChange struct {
	Balance              *AccountBalance `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EventAccountBalanceChange) Reset()         { *m = EventAccountBalanceChange{} }
func (m *EventAccountBalanceChange) String() string { return proto.CompactTextString(m) }
func (*EventAccountBalanceChange) ProtoMessage()    {}
func (*EventAccountBalanceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *EventAccountBalanceChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventAccountBalanceChange.Unmarshal(m, b)
}
func (m *EventAccountBalanceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventAccountBalanceChange.Marshal(b, m, deterministic)
}
func (m *EventAccountBalanceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAccountBalanceChange.Merge(m, src)
}
func (m *EventAccountBalanceChange) XXX_Size() int {
	return xxx_messageInfo_EventAccountBalanceChange.Size(m)
}
func (m *EventAccountBalanceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAccountBalanceChange.DiscardUnknown(m)
}

var xxx_messageInfo_EventAccountBalanceChange proto.InternalMessageInfo

func (m *EventAccountBalanceChange) GetBalance() *AccountBalance {
	if m != nil {
		return m.Balance
	}
	return nil
}

type EventBlockhainAccountUpdate struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventBlockhainAccountUpdate) Reset()         { *m = EventBlockhainAccountUpdate{} }
func (m *EventBlockhainAccountUpdate) String() string { return proto.CompactTextString(m) }
func (*EventBlockhainAccountUpdate) ProtoMessage()    {}
func (*EventBlockhainAccountUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *EventBlockhainAccountUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBlockhainAccountUpdate.Unmarshal(m, b)
}
func (m *EventBlockhainAccountUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBlockhainAccountUpdate.Marshal(b, m, deterministic)
}
func (m *EventBlockhainAccountUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBlockhainAccountUpdate.Merge(m, src)
}
func (m *EventBlockhainAccountUpdate) XXX_Size() int {
	return xxx_messageInfo_EventBlockhainAccountUpdate.Size(m)
}
func (m *EventBlockhainAccountUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBlockhainAccountUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EventBlockhainAccountUpdate proto.InternalMessageInfo

func (m *EventBlockhainAccountUpdate) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type Query_CreateAccount struct {
	OwnerId              string      `protobuf:"bytes,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	CurrencyId           string      `protobuf:"bytes,2,opt,name=currencyId,proto3" json:"currencyId,omitempty"`
	CurrencyName         string      `protobuf:"bytes,3,opt,name=currencyName,proto3" json:"currencyName,omitempty"`
	CurrencySymbol       string      `protobuf:"bytes,4,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	Type                 AccountType `protobuf:"varint,5,opt,name=type,proto3,enum=structs.AccountType" json:"type,omitempty"`
	Address              string      `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	BlockNumber          uint64      `protobuf:"varint,7,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Active               bool        `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Query_CreateAccount) Reset()         { *m = Query_CreateAccount{} }
func (m *Query_CreateAccount) String() string { return proto.CompactTextString(m) }
func (*Query_CreateAccount) ProtoMessage()    {}
func (*Query_CreateAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *Query_CreateAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query_CreateAccount.Unmarshal(m, b)
}
func (m *Query_CreateAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query_CreateAccount.Marshal(b, m, deterministic)
}
func (m *Query_CreateAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query_CreateAccount.Merge(m, src)
}
func (m *Query_CreateAccount) XXX_Size() int {
	return xxx_messageInfo_Query_CreateAccount.Size(m)
}
func (m *Query_CreateAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_Query_CreateAccount.DiscardUnknown(m)
}

var xxx_messageInfo_Query_CreateAccount proto.InternalMessageInfo

func (m *Query_CreateAccount) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Query_CreateAccount) GetCurrencyId() string {
	if m != nil {
		return m.CurrencyId
	}
	return ""
}

func (m *Query_CreateAccount) GetCurrencyName() string {
	if m != nil {
		return m.CurrencyName
	}
	return ""
}

func (m *Query_CreateAccount) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

func (m *Query_CreateAccount) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_INTERNAL
}

func (m *Query_CreateAccount) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Query_CreateAccount) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Query_CreateAccount) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Query_Account struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ParticipantId        string   `protobuf:"bytes,3,opt,name=participantId,proto3" json:"participantId,omitempty"`
	CurrencySymbol       string   `protobuf:"bytes,4,opt,name=currencySymbol,proto3" json:"currencySymbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query_Account) Reset()         { *m = Query_Account{} }
func (m *Query_Account) String() string { return proto.CompactTextString(m) }
func (*Query_Account) ProtoMessage()    {}
func (*Query_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *Query_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query_Account.Unmarshal(m, b)
}
func (m *Query_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query_Account.Marshal(b, m, deterministic)
}
func (m *Query_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query_Account.Merge(m, src)
}
func (m *Query_Account) XXX_Size() int {
	return xxx_messageInfo_Query_Account.Size(m)
}
func (m *Query_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Query_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Query_Account proto.InternalMessageInfo

func (m *Query_Account) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Query_Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Query_Account) GetParticipantId() string {
	if m != nil {
		return m.ParticipantId
	}
	return ""
}

func (m *Query_Account) GetCurrencySymbol() string {
	if m != nil {
		return m.CurrencySymbol
	}
	return ""
}

type Response_Account struct {
	Created              bool        `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Object               *Account    `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Items                []*Account  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	ItemsCount           uint32      `protobuf:"varint,4,opt,name=itemsCount,proto3" json:"itemsCount,omitempty"`
	QueryStatus          QueryStatus `protobuf:"varint,5,opt,name=QueryStatus,proto3,enum=structs.QueryStatus" json:"QueryStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response_Account) Reset()         { *m = Response_Account{} }
func (m *Response_Account) String() string { return proto.CompactTextString(m) }
func (*Response_Account) ProtoMessage()    {}
func (*Response_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *Response_Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Account.Unmarshal(m, b)
}
func (m *Response_Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Account.Marshal(b, m, deterministic)
}
func (m *Response_Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Account.Merge(m, src)
}
func (m *Response_Account) XXX_Size() int {
	return xxx_messageInfo_Response_Account.Size(m)
}
func (m *Response_Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Account proto.InternalMessageInfo

func (m *Response_Account) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response_Account) GetObject() *Account {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *Response_Account) GetItems() []*Account {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Response_Account) GetItemsCount() uint32 {
	if m != nil {
		return m.ItemsCount
	}
	return 0
}

func (m *Response_Account) GetQueryStatus() QueryStatus {
	if m != nil {
		return m.QueryStatus
	}
	return QueryStatus_Query_Missed
}

type Response_AccountBalance struct {
	Object               *AccountBalance `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	QueryStatus          QueryStatus     `protobuf:"varint,2,opt,name=QueryStatus,proto3,enum=structs.QueryStatus" json:"QueryStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response_AccountBalance) Reset()         { *m = Response_AccountBalance{} }
func (m *Response_AccountBalance) String() string { return proto.CompactTextString(m) }
func (*Response_AccountBalance) ProtoMessage()    {}
func (*Response_AccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *Response_AccountBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_AccountBalance.Unmarshal(m, b)
}
func (m *Response_AccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_AccountBalance.Marshal(b, m, deterministic)
}
func (m *Response_AccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_AccountBalance.Merge(m, src)
}
func (m *Response_AccountBalance) XXX_Size() int {
	return xxx_messageInfo_Response_AccountBalance.Size(m)
}
func (m *Response_AccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_AccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_Response_AccountBalance proto.InternalMessageInfo

func (m *Response_AccountBalance) GetObject() *AccountBalance {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *Response_AccountBalance) GetQueryStatus() QueryStatus {
	if m != nil {
		return m.QueryStatus
	}
	return QueryStatus_Query_Missed
}

type Account struct {
	// @inject_tag: bson:"_id,omitempty"
	BsonId               []byte         `protobuf:"bytes,8,opt,name=bsonId,proto3" json:"bsonId,omitempty" bson:"_id,omitempty"`
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              string         `protobuf:"bytes,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Currency             *Currency      `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Address              string         `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Type                 AccountType    `protobuf:"varint,6,opt,name=type,proto3,enum=structs.AccountType" json:"type,omitempty"`
	Status               Account_Status `protobuf:"varint,7,opt,name=status,proto3,enum=structs.Account_Status" json:"status,omitempty"`
	CreatedAt            string         `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Inc                  uint32         `protobuf:"varint,10,opt,name=inc,proto3" json:"inc,omitempty"`
	BlockNumber          uint64         `protobuf:"varint,11,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetBsonId() []byte {
	if m != nil {
		return m.BsonId
	}
	return nil
}

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *Account) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Account) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_INTERNAL
}

func (m *Account) GetStatus() Account_Status {
	if m != nil {
		return m.Status
	}
	return Account_INACTIVE
}

func (m *Account) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Account) GetInc() uint32 {
	if m != nil {
		return m.Inc
	}
	return 0
}

func (m *Account) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type AccountBalance struct {
	AccountId            string                         `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	AccountAddress       string                         `protobuf:"bytes,2,opt,name=accountAddress,proto3" json:"accountAddress,omitempty"`
	Available            float64                        `protobuf:"fixed64,3,opt,name=available,proto3" json:"available,omitempty"`
	Locked               float64                        `protobuf:"fixed64,4,opt,name=locked,proto3" json:"locked,omitempty"`
	Unconfirmed          float64                        `protobuf:"fixed64,5,opt,name=unconfirmed,proto3" json:"unconfirmed,omitempty"`
	AccountOwnerId       string                         `protobuf:"bytes,6,opt,name=accountOwnerId,proto3" json:"accountOwnerId,omitempty"`
	LockedReasons        []*AccountBalance_LockedReason `protobuf:"bytes,7,rep,name=lockedReasons,proto3" json:"lockedReasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *AccountBalance) Reset()         { *m = AccountBalance{} }
func (m *AccountBalance) String() string { return proto.CompactTextString(m) }
func (*AccountBalance) ProtoMessage()    {}
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *AccountBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalance.Unmarshal(m, b)
}
func (m *AccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalance.Marshal(b, m, deterministic)
}
func (m *AccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalance.Merge(m, src)
}
func (m *AccountBalance) XXX_Size() int {
	return xxx_messageInfo_AccountBalance.Size(m)
}
func (m *AccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalance proto.InternalMessageInfo

func (m *AccountBalance) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AccountBalance) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *AccountBalance) GetAvailable() float64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *AccountBalance) GetLocked() float64 {
	if m != nil {
		return m.Locked
	}
	return 0
}

func (m *AccountBalance) GetUnconfirmed() float64 {
	if m != nil {
		return m.Unconfirmed
	}
	return 0
}

func (m *AccountBalance) GetAccountOwnerId() string {
	if m != nil {
		return m.AccountOwnerId
	}
	return ""
}

func (m *AccountBalance) GetLockedReasons() []*AccountBalance_LockedReason {
	if m != nil {
		return m.LockedReasons
	}
	return nil
}

type AccountBalance_LockedReason struct {
	ContractId           string                                    `protobuf:"bytes,1,opt,name=contractId,proto3" json:"contractId,omitempty"`
	OrderId              string                                    `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	WithdrawalOrderId    string                                    `protobuf:"bytes,3,opt,name=withdrawalOrderId,proto3" json:"withdrawalOrderId,omitempty"`
	Amount               float64                                   `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason               AccountBalance_LockedReason__LockedReason `protobuf:"varint,5,opt,name=reason,proto3,enum=structs.AccountBalance_LockedReason__LockedReason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *AccountBalance_LockedReason) Reset()         { *m = AccountBalance_LockedReason{} }
func (m *AccountBalance_LockedReason) String() string { return proto.CompactTextString(m) }
func (*AccountBalance_LockedReason) ProtoMessage()    {}
func (*AccountBalance_LockedReason) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9, 0}
}

func (m *AccountBalance_LockedReason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountBalance_LockedReason.Unmarshal(m, b)
}
func (m *AccountBalance_LockedReason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountBalance_LockedReason.Marshal(b, m, deterministic)
}
func (m *AccountBalance_LockedReason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalance_LockedReason.Merge(m, src)
}
func (m *AccountBalance_LockedReason) XXX_Size() int {
	return xxx_messageInfo_AccountBalance_LockedReason.Size(m)
}
func (m *AccountBalance_LockedReason) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalance_LockedReason.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalance_LockedReason proto.InternalMessageInfo

func (m *AccountBalance_LockedReason) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *AccountBalance_LockedReason) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *AccountBalance_LockedReason) GetWithdrawalOrderId() string {
	if m != nil {
		return m.WithdrawalOrderId
	}
	return ""
}

func (m *AccountBalance_LockedReason) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AccountBalance_LockedReason) GetReason() AccountBalance_LockedReason__LockedReason {
	if m != nil {
		return m.Reason
	}
	return AccountBalance_LockedReason_REASON_UNVERIFIED_LOCKED
}

func init() {
	proto.RegisterEnum("structs.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("structs.Account_Status", Account_Status_name, Account_Status_value)
	proto.RegisterEnum("structs.AccountBalance_LockedReason__LockedReason", AccountBalance_LockedReason__LockedReason_name, AccountBalance_LockedReason__LockedReason_value)
	proto.RegisterType((*EventNewAccount)(nil), "structs.EventNewAccount")
	proto.RegisterType((*EventAccountUpdate)(nil), "structs.EventAccountUpdate")
	proto.RegisterType((*EventAccountBalanceChange)(nil), "structs.EventAccountBalanceChange")
	proto.RegisterType((*EventBlockhainAccountUpdate)(nil), "structs.EventBlockhainAccountUpdate")
	proto.RegisterType((*Query_CreateAccount)(nil), "structs.Query_CreateAccount")
	proto.RegisterType((*Query_Account)(nil), "structs.Query_Account")
	proto.RegisterType((*Response_Account)(nil), "structs.Response_Account")
	proto.RegisterType((*Response_AccountBalance)(nil), "structs.Response_AccountBalance")
	proto.RegisterType((*Account)(nil), "structs.Account")
	proto.RegisterType((*AccountBalance)(nil), "structs.AccountBalance")
	proto.RegisterType((*AccountBalance_LockedReason)(nil), "structs.AccountBalance.LockedReason")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceAccountClient is the client API for ServiceAccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceAccountClient interface {
	CreateAccount(ctx context.Context, in *Query_CreateAccount, opts ...grpc.CallOption) (*Response_Account, error)
	GetAllUserAccount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response_Account, error)
	GetAllAccount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response_Account, error)
	GetAccount(ctx context.Context, in *Query_Account, opts ...grpc.CallOption) (*Response_Account, error)
	GenerateInternalAccounts(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response_Account, error)
}

type serviceAccountClient struct {
	cc *grpc.ClientConn
}

func NewServiceAccountClient(cc *grpc.ClientConn) ServiceAccountClient {
	return &serviceAccountClient{cc}
}

func (c *serviceAccountClient) CreateAccount(ctx context.Context, in *Query_CreateAccount, opts ...grpc.CallOption) (*Response_Account, error) {
	out := new(Response_Account)
	err := c.cc.Invoke(ctx, "/structs.ServiceAccount/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountClient) GetAllUserAccount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response_Account, error) {
	out := new(Response_Account)
	err := c.cc.Invoke(ctx, "/structs.ServiceAccount/GetAllUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountClient) GetAllAccount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response_Account, error) {
	out := new(Response_Account)
	err := c.cc.Invoke(ctx, "/structs.ServiceAccount/GetAllAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountClient) GetAccount(ctx context.Context, in *Query_Account, opts ...grpc.CallOption) (*Response_Account, error) {
	out := new(Response_Account)
	err := c.cc.Invoke(ctx, "/structs.ServiceAccount/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountClient) GenerateInternalAccounts(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response_Account, error) {
	out := new(Response_Account)
	err := c.cc.Invoke(ctx, "/structs.ServiceAccount/GenerateInternalAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAccountServer is the server API for ServiceAccount service.
type ServiceAccountServer interface {
	CreateAccount(context.Context, *Query_CreateAccount) (*Response_Account, error)
	GetAllUserAccount(context.Context, *Empty) (*Response_Account, error)
	GetAllAccount(context.Context, *Empty) (*Response_Account, error)
	GetAccount(context.Context, *Query_Account) (*Response_Account, error)
	GenerateInternalAccounts(context.Context, *User) (*Response_Account, error)
}

func RegisterServiceAccountServer(s *grpc.Server, srv ServiceAccountServer) {
	s.RegisterService(&_ServiceAccount_serviceDesc, srv)
}

func _ServiceAccount_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query_CreateAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.ServiceAccount/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountServer).CreateAccount(ctx, req.(*Query_CreateAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccount_GetAllUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountServer).GetAllUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.ServiceAccount/GetAllUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountServer).GetAllUserAccount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccount_GetAllAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountServer).GetAllAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.ServiceAccount/GetAllAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountServer).GetAllAccount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccount_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query_Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.ServiceAccount/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountServer).GetAccount(ctx, req.(*Query_Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccount_GenerateInternalAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountServer).GenerateInternalAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.ServiceAccount/GenerateInternalAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountServer).GenerateInternalAccounts(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceAccount_serviceDesc = grpc.ServiceDesc{
	ServiceName: "structs.ServiceAccount",
	HandlerType: (*ServiceAccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _ServiceAccount_CreateAccount_Handler,
		},
		{
			MethodName: "GetAllUserAccount",
			Handler:    _ServiceAccount_GetAllUserAccount_Handler,
		},
		{
			MethodName: "GetAllAccount",
			Handler:    _ServiceAccount_GetAllAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _ServiceAccount_GetAccount_Handler,
		},
		{
			MethodName: "GenerateInternalAccounts",
			Handler:    _ServiceAccount_GenerateInternalAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

// ServiceAccountBalanceClient is the client API for ServiceAccountBalance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceAccountBalanceClient interface {
	GetBalance(ctx context.Context, in *Query_Account, opts ...grpc.CallOption) (*Response_AccountBalance, error)
}

type serviceAccountBalanceClient struct {
	cc *grpc.ClientConn
}

func NewServiceAccountBalanceClient(cc *grpc.ClientConn) ServiceAccountBalanceClient {
	return &serviceAccountBalanceClient{cc}
}

func (c *serviceAccountBalanceClient) GetBalance(ctx context.Context, in *Query_Account, opts ...grpc.CallOption) (*Response_AccountBalance, error) {
	out := new(Response_AccountBalance)
	err := c.cc.Invoke(ctx, "/structs.ServiceAccountBalance/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAccountBalanceServer is the server API for ServiceAccountBalance service.
type ServiceAccountBalanceServer interface {
	GetBalance(context.Context, *Query_Account) (*Response_AccountBalance, error)
}

func RegisterServiceAccountBalanceServer(s *grpc.Server, srv ServiceAccountBalanceServer) {
	s.RegisterService(&_ServiceAccountBalance_serviceDesc, srv)
}

func _ServiceAccountBalance_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query_Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountBalanceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.ServiceAccountBalance/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountBalanceServer).GetBalance(ctx, req.(*Query_Account))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceAccountBalance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "structs.ServiceAccountBalance",
	HandlerType: (*ServiceAccountBalanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _ServiceAccountBalance_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xdd, 0xd6, 0x69, 0x4f, 0x9a, 0x90, 0xce, 0x42, 0xeb, 0x2d, 0x15, 0x8a, 0xac, 0x55,
	0x15, 0xad, 0x20, 0x15, 0x41, 0x70, 0x05, 0xd2, 0x7a, 0x53, 0xef, 0xae, 0x4b, 0x9b, 0x88, 0x49,
	0xba, 0x0b, 0x57, 0xd5, 0xc4, 0x1e, 0x5a, 0x43, 0x32, 0x8e, 0xc6, 0x93, 0x56, 0xb9, 0xe5, 0x1d,
	0xb8, 0xe0, 0x06, 0xf1, 0x54, 0xbc, 0x01, 0xe2, 0x21, 0xb8, 0x41, 0x1e, 0xcf, 0xb8, 0xb6, 0xbb,
	0xed, 0x76, 0xf7, 0xce, 0xe7, 0x7c, 0x67, 0xbe, 0xf9, 0xce, 0xdf, 0x24, 0xd0, 0x20, 0x41, 0x10,
	0x2f, 0x98, 0xe8, 0xce, 0x79, 0x2c, 0x62, 0x54, 0x4b, 0x04, 0x5f, 0x04, 0x22, 0xd9, 0xdb, 0x0a,
	0xe2, 0xd9, 0x2c, 0x66, 0x99, 0x7b, 0xaf, 0x19, 0x2c, 0x38, 0xa7, 0x2c, 0x58, 0x2a, 0x1b, 0x16,
	0x09, 0xe5, 0xea, 0x7b, 0xff, 0x22, 0x8e, 0x2f, 0xa6, 0xf4, 0x90, 0xcc, 0xa3, 0x43, 0xc2, 0x58,
	0x2c, 0x88, 0x88, 0x62, 0x96, 0x64, 0xa8, 0xf3, 0x1d, 0x7c, 0xe4, 0x5d, 0x51, 0x26, 0x06, 0xf4,
	0xda, 0xcd, 0x6e, 0x42, 0x4f, 0xa1, 0xa6, 0x2e, 0xb5, 0x8d, 0xb6, 0xd1, 0xa9, 0xf7, 0x5a, 0x5d,
	0x75, 0x6b, 0x57, 0x85, 0x60, 0x1d, 0xe0, 0x3c, 0x03, 0x24, 0x8f, 0x2b, 0xe0, 0x6c, 0x1e, 0x12,
	0x41, 0xdf, 0x8b, 0x61, 0x00, 0x8f, 0x8b, 0x0c, 0xcf, 0xc9, 0x94, 0xb0, 0x80, 0xf6, 0x2f, 0x09,
	0xbb, 0xa0, 0xe8, 0x4b, 0xa8, 0x4d, 0x32, 0x87, 0x22, 0xda, 0xad, 0x12, 0xa9, 0x78, 0xac, 0xe3,
	0x1c, 0x1f, 0x3e, 0x95, 0x7c, 0xcf, 0xa7, 0x71, 0xf0, 0xeb, 0x25, 0x89, 0xd8, 0x87, 0x4b, 0xfb,
	0xc3, 0x84, 0x47, 0x3f, 0x2c, 0x28, 0x5f, 0x9e, 0xf7, 0x39, 0x25, 0x82, 0xea, 0x02, 0xd9, 0x50,
	0x8b, 0xaf, 0x19, 0xe5, 0x7e, 0x28, 0x39, 0x36, 0xb1, 0x36, 0xd1, 0x67, 0x00, 0xba, 0x13, 0x7e,
	0x68, 0x9b, 0x12, 0x2c, 0x78, 0x90, 0x03, 0x5b, 0xda, 0x1a, 0x90, 0x19, 0xb5, 0x57, 0x65, 0x44,
	0xc9, 0x87, 0x0e, 0x20, 0xef, 0xe6, 0x68, 0x39, 0x9b, 0xc4, 0x53, 0x7b, 0x4d, 0x46, 0x55, 0xbc,
	0xa8, 0x03, 0x6b, 0x62, 0x39, 0xa7, 0xf6, 0x7a, 0xdb, 0xe8, 0x34, 0x7b, 0x1f, 0x57, 0xd3, 0x18,
	0x2f, 0xe7, 0x14, 0xcb, 0x88, 0x54, 0x2f, 0x09, 0x43, 0x4e, 0x93, 0xc4, 0xb6, 0x32, 0xbd, 0xca,
	0x44, 0x6d, 0xa8, 0x4f, 0xd2, 0x3a, 0x0d, 0x16, 0xb3, 0x09, 0xe5, 0x76, 0xad, 0x6d, 0x74, 0xd6,
	0x70, 0xd1, 0x85, 0x76, 0xc0, 0x22, 0x81, 0x88, 0xae, 0xa8, 0xbd, 0xd1, 0x36, 0x3a, 0x1b, 0x58,
	0x59, 0xce, 0xef, 0x06, 0x34, 0xb2, 0xda, 0xe8, 0xaa, 0xec, 0xc3, 0xa6, 0x2a, 0x5c, 0x5e, 0x97,
	0x1b, 0x47, 0x51, 0x83, 0x59, 0xd6, 0xf0, 0x04, 0x1a, 0x73, 0xc2, 0x45, 0x14, 0x44, 0x73, 0x22,
	0xcf, 0x66, 0x45, 0x29, 0x3b, 0x1f, 0x5a, 0x15, 0xe7, 0x6f, 0x03, 0x5a, 0x98, 0x26, 0xf3, 0x98,
	0x25, 0xf4, 0xbc, 0xd0, 0xb0, 0x40, 0x76, 0x30, 0x13, 0xb6, 0x81, 0xb5, 0x89, 0x3a, 0x60, 0xc5,
	0x93, 0x5f, 0x68, 0x20, 0xa4, 0xaa, 0xb7, 0x4d, 0x83, 0xc2, 0xd1, 0x01, 0xac, 0x47, 0x82, 0xce,
	0x12, 0x7b, 0xb5, 0xbd, 0xfa, 0xd6, 0xc0, 0x0c, 0x4e, 0x47, 0x40, 0x7e, 0xf4, 0xe5, 0x8c, 0xa5,
	0x22, 0x1b, 0xb8, 0xe0, 0x41, 0xdf, 0x40, 0x5d, 0xd6, 0x6d, 0x24, 0x88, 0x58, 0x24, 0xb7, 0xba,
	0x57, 0xc0, 0x70, 0x31, 0xd0, 0xf9, 0xcd, 0x80, 0xdd, 0x6a, 0x62, 0x6a, 0xf8, 0xd1, 0x61, 0x9e,
	0xc5, 0x3b, 0xb6, 0x44, 0x27, 0x53, 0x11, 0x61, 0x3e, 0x54, 0xc4, 0x3f, 0x26, 0xd4, 0x74, 0x51,
	0x77, 0xc0, 0x9a, 0x24, 0x31, 0xf3, 0x43, 0x39, 0x19, 0x5b, 0x58, 0x59, 0xa8, 0x09, 0x66, 0xa4,
	0x07, 0xc0, 0x8c, 0xc2, 0xe2, 0xb6, 0x98, 0xe5, 0x6d, 0xf9, 0x02, 0x36, 0x74, 0xf7, 0x64, 0xa1,
	0xea, 0xbd, 0xed, 0x5c, 0x42, 0x5f, 0x01, 0x38, 0x0f, 0x49, 0x89, 0x5c, 0x35, 0x42, 0xeb, 0x19,
	0x91, 0x32, 0xf3, 0x55, 0xb0, 0xde, 0xb9, 0x0a, 0x87, 0x60, 0x25, 0x59, 0xce, 0x35, 0x19, 0x7b,
	0xab, 0x52, 0x5d, 0x95, 0xb6, 0x0a, 0x4b, 0xa7, 0x5a, 0xcd, 0x8a, 0x2b, 0xec, 0xcd, 0x6c, 0xaa,
	0x73, 0x07, 0x6a, 0xc1, 0x6a, 0xc4, 0x02, 0x1b, 0x64, 0x97, 0xd3, 0xcf, 0xea, 0x46, 0xd5, 0x6f,
	0x6d, 0x94, 0xe3, 0x80, 0x95, 0xdd, 0x81, 0xb6, 0x60, 0xc3, 0x1f, 0xb8, 0xfd, 0xb1, 0xff, 0xda,
	0x6b, 0xad, 0x20, 0x00, 0x4b, 0x7d, 0x1b, 0xce, 0x5f, 0xeb, 0xd0, 0xac, 0xf4, 0xf8, 0xfe, 0xf5,
	0x3a, 0x80, 0xa6, 0x32, 0xdc, 0xd2, 0x96, 0x55, 0xbc, 0x92, 0xe5, 0x8a, 0x44, 0x53, 0x32, 0x99,
	0x66, 0xaf, 0x8f, 0x81, 0x6f, 0x1c, 0x69, 0x4b, 0x53, 0xa1, 0x34, 0x94, 0xed, 0x30, 0xb0, 0xb2,
	0xd2, 0xa4, 0x16, 0x2c, 0x88, 0xd9, 0xcf, 0x11, 0x9f, 0xd1, 0x50, 0x56, 0xdf, 0xc0, 0x45, 0x57,
	0xe1, 0xfe, 0xa1, 0xea, 0xb5, 0x55, 0xba, 0x5f, 0x79, 0xd1, 0x31, 0x34, 0x32, 0x4e, 0x4c, 0x49,
	0x12, 0xb3, 0xb4, 0x0d, 0xe9, 0x36, 0x3d, 0xb9, 0x63, 0x60, 0xbb, 0x27, 0x85, 0x60, 0x5c, 0x3e,
	0xba, 0xf7, 0x9f, 0x09, 0x5b, 0x45, 0x5c, 0xbe, 0xbe, 0x31, 0x13, 0x9c, 0x04, 0x37, 0x35, 0x2a,
	0x78, 0xe4, 0x24, 0xf2, 0xb0, 0x34, 0x89, 0x99, 0x89, 0x3e, 0x87, 0xed, 0xeb, 0x48, 0x5c, 0x86,
	0x9c, 0x5c, 0x93, 0xe9, 0x50, 0xc5, 0x64, 0xef, 0xd0, 0x6d, 0x40, 0xbe, 0x89, 0xb3, 0x7c, 0xbd,
	0x0d, 0xac, 0x2c, 0x74, 0x0c, 0x16, 0x97, 0x4a, 0xd4, 0x56, 0xf7, 0x1e, 0x92, 0x55, 0xf7, 0xbc,
	0x94, 0xa3, 0x62, 0x70, 0xfe, 0x34, 0xa0, 0x51, 0x42, 0xd0, 0x3e, 0xd8, 0xd8, 0x73, 0x47, 0xc3,
	0xc1, 0xf9, 0xd9, 0xe0, 0xb5, 0x87, 0xfd, 0x17, 0xbe, 0x77, 0x74, 0x7e, 0x32, 0xec, 0x7f, 0xef,
	0x1d, 0xb5, 0x56, 0xd0, 0x1e, 0xec, 0x28, 0xb4, 0x3f, 0x1c, 0x8c, 0xb1, 0xdb, 0x1f, 0x6b, 0xcc,
	0x40, 0xbb, 0xf0, 0x48, 0x61, 0x43, 0x7c, 0xe4, 0x61, 0x0d, 0x98, 0x05, 0xca, 0xfe, 0xf0, 0xf4,
	0xd4, 0x1f, 0x8d, 0xfc, 0xe1, 0x40, 0xa3, 0xab, 0x05, 0xf4, 0x8d, 0x3f, 0x7e, 0x75, 0x84, 0xdd,
	0x37, 0xee, 0x89, 0x46, 0xd7, 0x9e, 0x7e, 0x0d, 0xf5, 0xc2, 0x7a, 0x65, 0xb3, 0x3c, 0xf6, 0xf0,
	0xc0, 0x3d, 0x69, 0xad, 0xa4, 0x96, 0xf7, 0xa3, 0xb2, 0x8c, 0x74, 0xb2, 0x47, 0x3f, 0x8d, 0xc6,
	0xde, 0x69, 0xcb, 0xec, 0xfd, 0x6b, 0x42, 0x73, 0x44, 0xf9, 0x55, 0x14, 0xe4, 0x3f, 0xa7, 0xc7,
	0xd0, 0x28, 0xff, 0xbe, 0xee, 0x97, 0x1f, 0xa2, 0xf2, 0xaf, 0xef, 0xde, 0xe3, 0x1c, 0xad, 0x3e,
	0x87, 0xce, 0x0a, 0x7a, 0x06, 0xdb, 0x2f, 0xa9, 0x70, 0xa7, 0xd3, 0xb3, 0x84, 0x72, 0xcd, 0xd7,
	0xcc, 0x4f, 0x78, 0xb3, 0xb9, 0x58, 0xde, 0xcf, 0xf0, 0x2d, 0x34, 0x32, 0x86, 0x0f, 0x3a, 0xed,
	0x02, 0xa4, 0xa7, 0xf5, 0x13, 0x59, 0x49, 0xe4, 0x41, 0x29, 0xbc, 0x00, 0xfb, 0x25, 0x65, 0x94,
	0x13, 0x41, 0x7d, 0x26, 0x28, 0x67, 0x44, 0x4b, 0x49, 0x50, 0x23, 0x3f, 0x98, 0xe6, 0x77, 0x2f,
	0x4f, 0x8f, 0xc0, 0x27, 0xe5, 0x42, 0xeb, 0x97, 0xe4, 0x95, 0xd4, 0xa8, 0xad, 0xbb, 0x34, 0xb6,
	0xef, 0xe4, 0x56, 0x27, 0x9d, 0x95, 0x89, 0x25, 0xff, 0x43, 0x7e, 0xf5, 0x7f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xad, 0x15, 0xf8, 0xcc, 0xa5, 0x0a, 0x00, 0x00,
}
