// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment_system.proto

package structs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventEthInOutDirection int32

const (
	EventEthInOut_UNDIRECT EventEthInOutDirection = 0
	EventEthInOut_IN       EventEthInOutDirection = 1
	EventEthInOut_OUT      EventEthInOutDirection = 2
)

var EventEthInOutDirection_name = map[int32]string{
	0: "UNDIRECT",
	1: "IN",
	2: "OUT",
}

var EventEthInOutDirection_value = map[string]int32{
	"UNDIRECT": 0,
	"IN":       1,
	"OUT":      2,
}

func (x EventEthInOutDirection) String() string {
	return proto.EnumName(EventEthInOutDirection_name, int32(x))
}

func (EventEthInOutDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{4, 0}
}

type EventPaySystemRawTx struct {
	Raw                  *Query_RawTx `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EventPaySystemRawTx) Reset()         { *m = EventPaySystemRawTx{} }
func (m *EventPaySystemRawTx) String() string { return proto.CompactTextString(m) }
func (*EventPaySystemRawTx) ProtoMessage()    {}
func (*EventPaySystemRawTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{0}
}

func (m *EventPaySystemRawTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventPaySystemRawTx.Unmarshal(m, b)
}
func (m *EventPaySystemRawTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventPaySystemRawTx.Marshal(b, m, deterministic)
}
func (m *EventPaySystemRawTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPaySystemRawTx.Merge(m, src)
}
func (m *EventPaySystemRawTx) XXX_Size() int {
	return xxx_messageInfo_EventPaySystemRawTx.Size(m)
}
func (m *EventPaySystemRawTx) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPaySystemRawTx.DiscardUnknown(m)
}

var xxx_messageInfo_EventPaySystemRawTx proto.InternalMessageInfo

func (m *EventPaySystemRawTx) GetRaw() *Query_RawTx {
	if m != nil {
		return m.Raw
	}
	return nil
}

type EventRelatedPaySystemTx struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	RelatedId            string   `protobuf:"bytes,2,opt,name=relatedId,proto3" json:"relatedId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRelatedPaySystemTx) Reset()         { *m = EventRelatedPaySystemTx{} }
func (m *EventRelatedPaySystemTx) String() string { return proto.CompactTextString(m) }
func (*EventRelatedPaySystemTx) ProtoMessage()    {}
func (*EventRelatedPaySystemTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{1}
}

func (m *EventRelatedPaySystemTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRelatedPaySystemTx.Unmarshal(m, b)
}
func (m *EventRelatedPaySystemTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRelatedPaySystemTx.Marshal(b, m, deterministic)
}
func (m *EventRelatedPaySystemTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRelatedPaySystemTx.Merge(m, src)
}
func (m *EventRelatedPaySystemTx) XXX_Size() int {
	return xxx_messageInfo_EventRelatedPaySystemTx.Size(m)
}
func (m *EventRelatedPaySystemTx) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRelatedPaySystemTx.DiscardUnknown(m)
}

var xxx_messageInfo_EventRelatedPaySystemTx proto.InternalMessageInfo

func (m *EventRelatedPaySystemTx) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *EventRelatedPaySystemTx) GetRelatedId() string {
	if m != nil {
		return m.RelatedId
	}
	return ""
}

type EventPaySystemAdded struct {
	Currency             *Currency `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EventPaySystemAdded) Reset()         { *m = EventPaySystemAdded{} }
func (m *EventPaySystemAdded) String() string { return proto.CompactTextString(m) }
func (*EventPaySystemAdded) ProtoMessage()    {}
func (*EventPaySystemAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{2}
}

func (m *EventPaySystemAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventPaySystemAdded.Unmarshal(m, b)
}
func (m *EventPaySystemAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventPaySystemAdded.Marshal(b, m, deterministic)
}
func (m *EventPaySystemAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPaySystemAdded.Merge(m, src)
}
func (m *EventPaySystemAdded) XXX_Size() int {
	return xxx_messageInfo_EventPaySystemAdded.Size(m)
}
func (m *EventPaySystemAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPaySystemAdded.DiscardUnknown(m)
}

var xxx_messageInfo_EventPaySystemAdded proto.InternalMessageInfo

func (m *EventPaySystemAdded) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type PaymentSystem struct {
	Currency             *Currency `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PaymentSystem) Reset()         { *m = PaymentSystem{} }
func (m *PaymentSystem) String() string { return proto.CompactTextString(m) }
func (*PaymentSystem) ProtoMessage()    {}
func (*PaymentSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{3}
}

func (m *PaymentSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentSystem.Unmarshal(m, b)
}
func (m *PaymentSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentSystem.Marshal(b, m, deterministic)
}
func (m *PaymentSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentSystem.Merge(m, src)
}
func (m *PaymentSystem) XXX_Size() int {
	return xxx_messageInfo_PaymentSystem.Size(m)
}
func (m *PaymentSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentSystem.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentSystem proto.InternalMessageInfo

func (m *PaymentSystem) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type EventEthInOut struct {
	Token                string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Address              string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	TxId                 string                 `protobuf:"bytes,3,opt,name=txId,proto3" json:"txId,omitempty"`
	Amount               string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 EventEthInOutDirection `protobuf:"varint,5,opt,name=type,proto3,enum=structs.EventEthInOutDirection" json:"type,omitempty"`
	ContractAddress      string                 `protobuf:"bytes,6,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EventEthInOut) Reset()         { *m = EventEthInOut{} }
func (m *EventEthInOut) String() string { return proto.CompactTextString(m) }
func (*EventEthInOut) ProtoMessage()    {}
func (*EventEthInOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{4}
}

func (m *EventEthInOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventEthInOut.Unmarshal(m, b)
}
func (m *EventEthInOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventEthInOut.Marshal(b, m, deterministic)
}
func (m *EventEthInOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventEthInOut.Merge(m, src)
}
func (m *EventEthInOut) XXX_Size() int {
	return xxx_messageInfo_EventEthInOut.Size(m)
}
func (m *EventEthInOut) XXX_DiscardUnknown() {
	xxx_messageInfo_EventEthInOut.DiscardUnknown(m)
}

var xxx_messageInfo_EventEthInOut proto.InternalMessageInfo

func (m *EventEthInOut) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *EventEthInOut) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EventEthInOut) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *EventEthInOut) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *EventEthInOut) GetType() EventEthInOutDirection {
	if m != nil {
		return m.Type
	}
	return EventEthInOut_UNDIRECT
}

func (m *EventEthInOut) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

type EthAddress struct {
	Address              string           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	DerivationPath       string           `protobuf:"bytes,2,opt,name=derivationPath,proto3" json:"derivationPath,omitempty"`
	ContractAddress      string           `protobuf:"bytes,3,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	EthBalance           string           `protobuf:"bytes,5,opt,name=ethBalance,proto3" json:"ethBalance,omitempty"`
	TokenBalance         string           `protobuf:"bytes,6,opt,name=tokenBalance,proto3" json:"tokenBalance,omitempty"`
	EthTxs               []*EventEthInOut `protobuf:"bytes,7,rep,name=ethTxs,proto3" json:"ethTxs,omitempty"`
	TokenTxs             []*EventEthInOut `protobuf:"bytes,8,rep,name=tokenTxs,proto3" json:"tokenTxs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EthAddress) Reset()         { *m = EthAddress{} }
func (m *EthAddress) String() string { return proto.CompactTextString(m) }
func (*EthAddress) ProtoMessage()    {}
func (*EthAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{5}
}

func (m *EthAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthAddress.Unmarshal(m, b)
}
func (m *EthAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthAddress.Marshal(b, m, deterministic)
}
func (m *EthAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthAddress.Merge(m, src)
}
func (m *EthAddress) XXX_Size() int {
	return xxx_messageInfo_EthAddress.Size(m)
}
func (m *EthAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_EthAddress.DiscardUnknown(m)
}

var xxx_messageInfo_EthAddress proto.InternalMessageInfo

func (m *EthAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EthAddress) GetDerivationPath() string {
	if m != nil {
		return m.DerivationPath
	}
	return ""
}

func (m *EthAddress) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *EthAddress) GetEthBalance() string {
	if m != nil {
		return m.EthBalance
	}
	return ""
}

func (m *EthAddress) GetTokenBalance() string {
	if m != nil {
		return m.TokenBalance
	}
	return ""
}

func (m *EthAddress) GetEthTxs() []*EventEthInOut {
	if m != nil {
		return m.EthTxs
	}
	return nil
}

func (m *EthAddress) GetTokenTxs() []*EventEthInOut {
	if m != nil {
		return m.TokenTxs
	}
	return nil
}

type Query_FundWithdrawEth struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query_FundWithdrawEth) Reset()         { *m = Query_FundWithdrawEth{} }
func (m *Query_FundWithdrawEth) String() string { return proto.CompactTextString(m) }
func (*Query_FundWithdrawEth) ProtoMessage()    {}
func (*Query_FundWithdrawEth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{6}
}

func (m *Query_FundWithdrawEth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query_FundWithdrawEth.Unmarshal(m, b)
}
func (m *Query_FundWithdrawEth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query_FundWithdrawEth.Marshal(b, m, deterministic)
}
func (m *Query_FundWithdrawEth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query_FundWithdrawEth.Merge(m, src)
}
func (m *Query_FundWithdrawEth) XXX_Size() int {
	return xxx_messageInfo_Query_FundWithdrawEth.Size(m)
}
func (m *Query_FundWithdrawEth) XXX_DiscardUnknown() {
	xxx_messageInfo_Query_FundWithdrawEth.DiscardUnknown(m)
}

var xxx_messageInfo_Query_FundWithdrawEth proto.InternalMessageInfo

func (m *Query_FundWithdrawEth) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Query_FundWithdrawEth) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Response_EthAddress struct {
	Addresses            []*EthAddress `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response_EthAddress) Reset()         { *m = Response_EthAddress{} }
func (m *Response_EthAddress) String() string { return proto.CompactTextString(m) }
func (*Response_EthAddress) ProtoMessage()    {}
func (*Response_EthAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e4c127494bc4dfe, []int{7}
}

func (m *Response_EthAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_EthAddress.Unmarshal(m, b)
}
func (m *Response_EthAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_EthAddress.Marshal(b, m, deterministic)
}
func (m *Response_EthAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_EthAddress.Merge(m, src)
}
func (m *Response_EthAddress) XXX_Size() int {
	return xxx_messageInfo_Response_EthAddress.Size(m)
}
func (m *Response_EthAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_EthAddress.DiscardUnknown(m)
}

var xxx_messageInfo_Response_EthAddress proto.InternalMessageInfo

func (m *Response_EthAddress) GetAddresses() []*EthAddress {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterEnum("structs.EventEthInOutDirection", EventEthInOutDirection_name, EventEthInOutDirection_value)
	proto.RegisterType((*EventPaySystemRawTx)(nil), "structs.EventPaySystemRawTx")
	proto.RegisterType((*EventRelatedPaySystemTx)(nil), "structs.EventRelatedPaySystemTx")
	proto.RegisterType((*EventPaySystemAdded)(nil), "structs.EventPaySystemAdded")
	proto.RegisterType((*PaymentSystem)(nil), "structs.PaymentSystem")
	proto.RegisterType((*EventEthInOut)(nil), "structs.EventEthInOut")
	proto.RegisterType((*EthAddress)(nil), "structs.EthAddress")
	proto.RegisterType((*Query_FundWithdrawEth)(nil), "structs.Query_FundWithdrawEth")
	proto.RegisterType((*Response_EthAddress)(nil), "structs.Response_EthAddress")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentSystemRegistryClient is the client API for PaymentSystemRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentSystemRegistryClient interface {
	GenerateAccount(ctx context.Context, in *Currency, opts ...grpc.CallOption) (*Account, error)
}

type paymentSystemRegistryClient struct {
	cc *grpc.ClientConn
}

func NewPaymentSystemRegistryClient(cc *grpc.ClientConn) PaymentSystemRegistryClient {
	return &paymentSystemRegistryClient{cc}
}

func (c *paymentSystemRegistryClient) GenerateAccount(ctx context.Context, in *Currency, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/structs.PaymentSystemRegistry/GenerateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentSystemRegistryServer is the server API for PaymentSystemRegistry service.
type PaymentSystemRegistryServer interface {
	GenerateAccount(context.Context, *Currency) (*Account, error)
}

func RegisterPaymentSystemRegistryServer(s *grpc.Server, srv PaymentSystemRegistryServer) {
	s.RegisterService(&_PaymentSystemRegistry_serviceDesc, srv)
}

func _PaymentSystemRegistry_GenerateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Currency)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentSystemRegistryServer).GenerateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.PaymentSystemRegistry/GenerateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentSystemRegistryServer).GenerateAccount(ctx, req.(*Currency))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentSystemRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "structs.PaymentSystemRegistry",
	HandlerType: (*PaymentSystemRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAccount",
			Handler:    _PaymentSystemRegistry_GenerateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_system.proto",
}

// EthTokenServiceClient is the client API for EthTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EthTokenServiceClient interface {
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response_EthAddress, error)
	FundFee(ctx context.Context, in *Query_FundWithdrawEth, opts ...grpc.CallOption) (*Bool, error)
	Withdraw(ctx context.Context, in *Query_FundWithdrawEth, opts ...grpc.CallOption) (*Bool, error)
}

type ethTokenServiceClient struct {
	cc *grpc.ClientConn
}

func NewEthTokenServiceClient(cc *grpc.ClientConn) EthTokenServiceClient {
	return &ethTokenServiceClient{cc}
}

func (c *ethTokenServiceClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response_EthAddress, error) {
	out := new(Response_EthAddress)
	err := c.cc.Invoke(ctx, "/structs.EthTokenService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTokenServiceClient) FundFee(ctx context.Context, in *Query_FundWithdrawEth, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/structs.EthTokenService/FundFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ethTokenServiceClient) Withdraw(ctx context.Context, in *Query_FundWithdrawEth, opts ...grpc.CallOption) (*Bool, error) {
	out := new(Bool)
	err := c.cc.Invoke(ctx, "/structs.EthTokenService/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EthTokenServiceServer is the server API for EthTokenService service.
type EthTokenServiceServer interface {
	GetAll(context.Context, *Empty) (*Response_EthAddress, error)
	FundFee(context.Context, *Query_FundWithdrawEth) (*Bool, error)
	Withdraw(context.Context, *Query_FundWithdrawEth) (*Bool, error)
}

func RegisterEthTokenServiceServer(s *grpc.Server, srv EthTokenServiceServer) {
	s.RegisterService(&_EthTokenService_serviceDesc, srv)
}

func _EthTokenService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTokenServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.EthTokenService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTokenServiceServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTokenService_FundFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query_FundWithdrawEth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTokenServiceServer).FundFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.EthTokenService/FundFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTokenServiceServer).FundFee(ctx, req.(*Query_FundWithdrawEth))
	}
	return interceptor(ctx, in, info, handler)
}

func _EthTokenService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query_FundWithdrawEth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EthTokenServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/structs.EthTokenService/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EthTokenServiceServer).Withdraw(ctx, req.(*Query_FundWithdrawEth))
	}
	return interceptor(ctx, in, info, handler)
}

var _EthTokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "structs.EthTokenService",
	HandlerType: (*EthTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _EthTokenService_GetAll_Handler,
		},
		{
			MethodName: "FundFee",
			Handler:    _EthTokenService_FundFee_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _EthTokenService_Withdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_system.proto",
}

func init() { proto.RegisterFile("payment_system.proto", fileDescriptor_8e4c127494bc4dfe) }

var fileDescriptor_8e4c127494bc4dfe = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x6a, 0xdb, 0x40,
	0x10, 0xb5, 0xec, 0xc4, 0x97, 0x49, 0xec, 0x38, 0x9b, 0x4b, 0x8d, 0x09, 0xc1, 0xe8, 0x21, 0x98,
	0x42, 0x1d, 0xea, 0xf6, 0x21, 0xb4, 0xb4, 0xe0, 0x24, 0x4e, 0x6a, 0x0a, 0xb9, 0x28, 0x0e, 0x7d,
	0x0c, 0x5b, 0x69, 0x88, 0x44, 0xed, 0x5d, 0xb3, 0x1a, 0x27, 0xd6, 0xdf, 0xf4, 0x63, 0xfa, 0x4f,
	0x7d, 0x2d, 0x5a, 0xad, 0xe5, 0x4b, 0x4d, 0x20, 0x6f, 0x9a, 0x99, 0x73, 0x86, 0x73, 0xce, 0xae,
	0x16, 0x76, 0x47, 0x3c, 0x1a, 0xa2, 0xa0, 0x87, 0x30, 0x0a, 0x09, 0x87, 0xad, 0x91, 0x92, 0x24,
	0x59, 0x21, 0x24, 0x35, 0x76, 0x29, 0xac, 0x6f, 0xba, 0x72, 0x38, 0x94, 0x22, 0x69, 0xd7, 0x2b,
	0xee, 0x58, 0x29, 0x14, 0x6e, 0x64, 0xea, 0x32, 0x77, 0x5d, 0x39, 0x16, 0x64, 0xca, 0x6d, 0x52,
	0x5c, 0x84, 0xdc, 0xa5, 0x20, 0x65, 0x6c, 0x48, 0xe5, 0xa1, 0x32, 0xc5, 0xc1, 0xa3, 0x94, 0x8f,
	0x03, 0x3c, 0xe6, 0xa3, 0xe0, 0x98, 0x0b, 0x21, 0x89, 0xc7, 0xc8, 0x30, 0x99, 0xda, 0x5f, 0x60,
	0xa7, 0xfb, 0x84, 0x82, 0x6e, 0x78, 0x74, 0xa7, 0xb5, 0x38, 0xfc, 0xb9, 0x3f, 0x61, 0x47, 0x90,
	0x53, 0xfc, 0xb9, 0x66, 0x35, 0xac, 0xe6, 0x46, 0x7b, 0xb7, 0x65, 0x84, 0xb5, 0x6e, 0xc7, 0xa8,
	0xa2, 0x07, 0x0d, 0x71, 0x62, 0x80, 0xfd, 0x1d, 0xde, 0x68, 0xba, 0x83, 0x03, 0x4e, 0xe8, 0xa5,
	0x5b, 0xfa, 0x13, 0xc6, 0x60, 0x8d, 0x26, 0x3d, 0x4f, 0xef, 0x28, 0x39, 0xfa, 0x9b, 0x1d, 0x40,
	0x49, 0x25, 0xc8, 0x9e, 0x57, 0xcb, 0xea, 0xc1, 0xac, 0x61, 0x9f, 0x2f, 0x6b, 0xe9, 0x78, 0x1e,
	0x7a, 0xec, 0x1d, 0x14, 0xa7, 0x09, 0x18, 0x41, 0xdb, 0xa9, 0xa0, 0x33, 0x33, 0x70, 0x52, 0x88,
	0xfd, 0x15, 0xca, 0x37, 0x49, 0xba, 0xc9, 0x92, 0xd7, 0xf2, 0xff, 0x5a, 0x50, 0xd6, 0x32, 0xba,
	0xe4, 0xf7, 0xc4, 0xf5, 0x98, 0xd8, 0x2e, 0xac, 0x93, 0xfc, 0x85, 0xc2, 0x58, 0x49, 0x0a, 0x56,
	0x83, 0x02, 0xf7, 0x3c, 0x85, 0x61, 0x68, 0x9c, 0x4c, 0xcb, 0xd4, 0x79, 0x6e, 0xce, 0xf9, 0x3e,
	0xe4, 0xf9, 0x30, 0x3e, 0xb5, 0xda, 0x9a, 0xee, 0x9a, 0x8a, 0x7d, 0x84, 0x35, 0x8a, 0x46, 0x58,
	0x5b, 0x6f, 0x58, 0xcd, 0x4a, 0xbb, 0x91, 0x0a, 0x5b, 0x50, 0xd0, 0xf2, 0x02, 0x85, 0xfa, 0x80,
	0x1d, 0x8d, 0x66, 0x4d, 0xd8, 0x72, 0xa5, 0x20, 0xc5, 0x5d, 0xea, 0x18, 0x0d, 0x79, 0xbd, 0x76,
	0xb9, 0x6d, 0xbf, 0x85, 0x52, 0x4a, 0x66, 0x9b, 0x50, 0xbc, 0xbf, 0x3a, 0xef, 0x39, 0xdd, 0xb3,
	0x7e, 0x35, 0xc3, 0xf2, 0x90, 0xed, 0x5d, 0x55, 0x2d, 0x56, 0x80, 0xdc, 0xf5, 0x7d, 0xbf, 0x9a,
	0xb5, 0x7f, 0x67, 0x01, 0xba, 0xe4, 0x1b, 0xea, 0xbc, 0x41, 0x6b, 0xd1, 0xe0, 0x11, 0x54, 0x3c,
	0x54, 0xc1, 0x93, 0xbe, 0x49, 0x37, 0x9c, 0x7c, 0x93, 0xc0, 0x52, 0x77, 0x95, 0xcc, 0xdc, 0x4a,
	0x99, 0xec, 0x10, 0x00, 0xc9, 0x3f, 0xe5, 0x03, 0x2e, 0xdc, 0x24, 0x8c, 0x92, 0x33, 0xd7, 0x61,
	0x36, 0x6c, 0xea, 0xd4, 0xa7, 0x88, 0xc4, 0xed, 0x42, 0x8f, 0xb5, 0x20, 0x8f, 0xe4, 0xf7, 0x27,
	0x61, 0xad, 0xd0, 0xc8, 0x35, 0x37, 0xda, 0xfb, 0xab, 0xc3, 0x74, 0x0c, 0x8a, 0xb5, 0xa1, 0xa8,
	0xf9, 0x31, 0xa3, 0xf8, 0x22, 0x23, 0xc5, 0xd9, 0x3d, 0xd8, 0x4b, 0xfe, 0x81, 0x8b, 0xb1, 0xf0,
	0x7e, 0x04, 0xe4, 0x7b, 0x8a, 0x3f, 0x77, 0xc9, 0x7f, 0x21, 0xac, 0xd9, 0xc9, 0xc7, 0x21, 0x59,
	0xd3, 0x93, 0xb7, 0xbf, 0xc1, 0x8e, 0x83, 0xe1, 0x48, 0x8a, 0x10, 0x1f, 0xe6, 0x52, 0x7f, 0x0f,
	0x25, 0xc3, 0xc4, 0x78, 0x55, 0x2c, 0x6b, 0x67, 0x26, 0x2b, 0xc5, 0x39, 0x33, 0x54, 0xfb, 0x16,
	0xf6, 0x16, 0x6e, 0xbc, 0x83, 0x8f, 0x41, 0x48, 0x2a, 0x62, 0x27, 0xb0, 0x75, 0x89, 0x02, 0x15,
	0x27, 0xec, 0x24, 0x6f, 0x06, 0xfb, 0xff, 0xea, 0xd7, 0xab, 0x69, 0xcb, 0x80, 0xec, 0x4c, 0xfb,
	0x8f, 0x05, 0x5b, 0x5d, 0xf2, 0xfb, 0xb1, 0xef, 0x3b, 0x54, 0x4f, 0x81, 0x8b, 0xec, 0x04, 0xf2,
	0x97, 0x48, 0x9d, 0xc1, 0x80, 0x55, 0x66, 0x82, 0x86, 0x23, 0x8a, 0xea, 0x07, 0x69, 0xbd, 0xc2,
	0x91, 0x9d, 0x61, 0x9f, 0xa0, 0x10, 0xe7, 0x75, 0x81, 0xc8, 0x0e, 0x97, 0xde, 0x92, 0xa5, 0x1c,
	0xeb, 0xe5, 0x74, 0x7e, 0x2a, 0xe5, 0xc0, 0xce, 0xb0, 0xcf, 0x50, 0x9c, 0xce, 0x5f, 0x4d, 0xfe,
	0x99, 0xd7, 0x8f, 0xdc, 0x87, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0xdc, 0x38, 0xcf, 0x70,
	0x05, 0x00, 0x00,
}
