// Code generated by go-swagger; DO NOT EDIT.

package service_commission

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "mxp/mxp-protobuf/swg/clientswg/models"
)

// NewCalcParams creates a new CalcParams object
// with the default values initialized.
func NewCalcParams() *CalcParams {
	var ()
	return &CalcParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCalcParamsWithTimeout creates a new CalcParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCalcParamsWithTimeout(timeout time.Duration) *CalcParams {
	var ()
	return &CalcParams{

		timeout: timeout,
	}
}

// NewCalcParamsWithContext creates a new CalcParams object
// with the default values initialized, and the ability to set a context for a request
func NewCalcParamsWithContext(ctx context.Context) *CalcParams {
	var ()
	return &CalcParams{

		Context: ctx,
	}
}

// NewCalcParamsWithHTTPClient creates a new CalcParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCalcParamsWithHTTPClient(client *http.Client) *CalcParams {
	var ()
	return &CalcParams{
		HTTPClient: client,
	}
}

/*CalcParams contains all the parameters to send to the API endpoint
for the calc operation typically these are written to a http.Request
*/
type CalcParams struct {

	/*Body*/
	Body *models.OrderQueryCalculateCommission

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the calc params
func (o *CalcParams) WithTimeout(timeout time.Duration) *CalcParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the calc params
func (o *CalcParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the calc params
func (o *CalcParams) WithContext(ctx context.Context) *CalcParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the calc params
func (o *CalcParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the calc params
func (o *CalcParams) WithHTTPClient(client *http.Client) *CalcParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the calc params
func (o *CalcParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the calc params
func (o *CalcParams) WithBody(body *models.OrderQueryCalculateCommission) *CalcParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the calc params
func (o *CalcParams) SetBody(body *models.OrderQueryCalculateCommission) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CalcParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
